name: develop-d3-chart-server.zip

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  DockerImage:
    name: Lambda Zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CASTLECI_DEVELOP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CASTLECI_DEVELOP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CASTLECI_DEVELOP_AWS_REGION }}
      - name: Create .zip and Upload to S3
        env:
          S3_BUCKET: ${{ secrets.CASTLECI_DEVELOP_S3_BUCKET_LAMBDA_ZIPS }}
          ZIPFILE: develop-d3-chart-server.zip
        run: |
          zip -j ${ZIPFILE} ${GITHUB_WORKSPACE} --exclude .env
          aws s3 cp ${ZIPFILE} s3://${S3_BUCKET}/${ZIPFILE}
