name: Build and Test

on:
  push:
    branches: ['main']
    tags:
      - 'v*.*.*'
  pull_request:
    branches: ['main']
jobs:
  Tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          cd ${GITHUB_WORKSPACE}
          npm install --omit=dev
      - name: Run Tests
        run: echo "TESTS NOT YET IMPLEMENTED"
